### ISSUE TITLE
Feature request — converting between different Indic scripts

### ISSUE THREAD

**Issue by madmansnest** [mohancloudworld/Parivartan#1]
It’d be great to add a mode to convert between different Indic sctipts if possible.

**Comment by mohancloudworld** [comment]
This feature is already supported and I already mentioned it in the README. 

Please follow the following procedure:
1) select the text (Indic script) on the web-page
2) right click and select the "Indian/English(ITRANS)" option from the "Parivartan" menu
3) then select the desired language (Indic script)

**Comment by madmansnest** [comment]
Many thanks!
